name: Release

on:
  push:
    tags:
      - v[0-9]+.*
  pull_request:
    branches: [ master ]

jobs:
  create-release:
    name: Release client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: cargo package

      - uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
